services:
  proxy:
    image: localhost/nginx:latest
    ports:
      - 80:80
    networks:
      - local
      - nat
    depends_on:
      - flask-app
    entrypoint: ["nginx", "-g", "daemon off;"]

  flask-app:
    image: localhost/flask-app:latest
    networks:
      - local
      - nat

networks:
  local:
    internal: true
    driver: ipvlan
  nat:
    driver: bridge